@extends('template.template')

@section('content-header')

<link rel="stylesheet" href="\plugins\datatables\dataTables.bootstrap.css">
<style>
 
</style>
@endsection

@section('content')


    <section id="ClientSearch">
        <div class="row">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                        <h3 class="bold">Search Client</h3>
                    </div>
                </div>
            </div>
             @if (Session::has('message'))
                <div class="col-md-12 col-lg-12 col-xs-12 message-box">
                    <div class="alert alert-info">{{ Session::get('message') }}</div>
                </div>
            @endif
            <div class="col-md-12 col-lg-12 col-xs-12">
                {!! Form::open(['route' => 'admin.client.setfilter','autocomplete' => 'off']) !!}
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Search Fields<a class="btn btn-default pull-right btn-xs" data-toggle="modal" data-target="#modal-advanced-search"><i class="fa fa-plus"></i> Advanced Search Fields</a></div>

                        <div class="modal fade" id="modal-advanced-search" tabindex="-1" role="dialog">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">Add Advanced Fields to Search.</h4>
                              </div>
                              <div class="modal-body row">
                                    <div class="col-md-12">
                                        <div class="col-md-4">
                                            @if(session('client_search.city'))
                                            <input type="checkbox" name="" class="check_advanced_search1" checked><span> City</span>
                                            @else
                                            <input type="checkbox" name="" class="check_advanced_search1" ><span> City</span>
                                            @endif
                                        </div>
                                        <div class="col-md-4">
                                            @if(session('client_search.lead_generated_by'))
                                            <input type="checkbox" name="" class="check_advanced_search2" checked><span> Lead generated by</span>
                                            @else
                                            <input type="checkbox" name="" class="check_advanced_search2" ><span> Lead generated by</span>
                                            @endif
                                        </div>
                                        <div class="col-md-4">
                                            @if(session('client_search.billing_cycle_next_end_date'))
                                            <input type="checkbox" name="" class="check_advanced_search3" checked><span> Billing cycle next end date</span>
                                            @else
                                            <input type="checkbox" name="" class="check_advanced_search3" ><span> Billing cycle next end date</span>
                                            @endif
                                        </div>
                                        <div class="col-md-4">
                                            @if(session('client_search.invoice_method'))
                                            <input type="checkbox" name="" class="check_advanced_search4" checked><span> Invoice method</span>
                                            @else
                                            <input type="checkbox" name="" class="check_advanced_search4" ><span> Invoice method</span>
                                            @endif
                                        </div>
                                        <div class="col-md-4">
                                            @if(session('client_search.payment_method'))
                                            <input type="checkbox" name="" class="check_advanced_search5" checked><span> Payment method</span>
                                            @else
                                            <input type="checkbox" name="" class="check_advanced_search5" ><span> Payment method</span>
                                            @endif
                                        </div>
                                         
                                    </div>

                              </div>
                              <div class="modal-footer">
                                    <button class="btn btn-success btn-advanced-search" type="button"  data-dismiss="modal"> Apply</button>
                                    <button class="btn btn-danger" type="button"  data-dismiss="modal"><i calss="fa fa-times"></i> Cancel</button>
                              </div>
                            </div>
                          </div>
                        </div>


                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-4 form-group">
                                    <label>Client Status:</label>
                                    {!!  Form::select('status',$status,session('client_search.status'), ['class' => 'form-control changeStatus' ]) !!}
                                </div>
                            
                                <div class="col-md-4 form-group">
                                    <label>Client Name:</label>
                                    <input name="client_name" class="form-control " type="text" value="{{session('client_search.client_name')}}"  >
                                </div>
                                                             
                                
                                <div class="col-md-4 form-group">
                                    <label>Country:</label>
                                    {!!  Form::select('country',$country,session('client_search.country'), ['class' => 'form-control ']) !!}
                                </div>
                                 
                                <div class="col-md-4 form-group">
                                    <label>State:</label>
                                    <input name="state" class="form-control " type="text" value="{{session('client_search.state')}}">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label>Zip Code:</label>
                                    <input name="zip" class="form-control " type="text" value="{{session('client_search.zip')}}">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label>Worker Job Functions:</label>
                                    {!!  Form::select('job_function',$job_function,session('client_search.job_function'), ['class' => 'form-control ']) !!}
                                </div>
                            </div>
                       
                            <div class="row">
                                
                                <div class="col-md-4 form-group advanced_field1"  style="{{session('client_search.city') ? '':'display:none'}}">
                                    <label>City:</label>
                                    <input name="city" class="form-control  advanced_field1" type="text" value="{{session('client_search.city')}}">
                                </div>
                                <div class="col-md-4 form-group advanced_field2"  style="{{session('client_search.lead_generated_by') ? '':'display:none'}}">
                                    <label>Lead Generated By:</label>
                                    {!!  Form::select('lead_generated_by',$lead_generated_by,session('client_search.lead_generated_by'), ['class' => 'form-control advanced_field2']) !!}
                                    
                                </div>
                                <div class="col-md-4 form-group advanced_field3"  style="{{session('client_search.billing_cycle_next_end_date') ? '':'display:none'}}">
                                    <label>Billing Cycle - Next End Date :</label>
                                    <input name="billing_cycle_next_end_date" class="form-control  advanced_field3" type="date" value="{{session('client_search.billing_cycle_next_end_date')}}" >
                                </div>
                                
                                <div class="col-md-4 form-group advanced_field4"  style="{{session('client_search.invoice_method') ? '':'display:none'}}">
                                    <label>Invoice Method:</label>
                                    {!!  Form::select('invoice_method',$invoice_method,session('client_search.invoice_method'), ['class' => 'form-control  advanced_field4' ]) !!}
                                </div>
                                <div class="col-md-4 form-group advanced_field5"  style="{{session('client_search.payment_method') ? '':'display:none'}}">
                                    <label>Payment Method:</label>
                                    {!!  Form::select('payment_method',$payment_method,session('client_search.payment_method'), ['class' => 'form-control advanced_field5']) !!}
                                </div>
                                <div class="col-md-12 form-group ">
                                    <button type="submit" class="btn btn-success pull-right" style="margin-left: 10px"><i class="fa fa-search"></i> Search</button> 
                                    <a href="{{route('admin.client.resetfilter')}}" class="btn btn-warning pull-right"><i class="fa fa-remove"></i> Clear</a>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Search Result</div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="box-body table_group" style="overflow-x: scroll;">
                                    <table id="list_table" class="table table-hover text-center table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Status</th>
                                            <th>Client Name</th>
                                            <th>Country</th>
                                            <th>State</th>
                                            <th>Industry</th>
                                            <th>&nbsp;&nbsp;Action&nbsp;&nbsp;</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($clients as $client)
                                        <tr>
                                            <td>{{$status[$client->status]}}</td>
                                            <td>{{$client->client_name}}</td>
                                            <td>@if($client->country=="Other")
                                                {{$client->country_other}}
                                            @else
                                            US
                                            @endif
                                            </td>
                                            <td>{{$client->state}}</td>
                                            <td>{{$client->industry}}</td>
                                            <td>
                                                <a href="/admin/profileClient/{{$client->id}}" class="btn btn-success btn-xs"><i class="fa fa-edit"></i></a>
                                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-close"  data-toggle="modal" data-target="#modal-delete-{{$client->id}}"></i></a>
                                                @component('admin.client.components.deletemodal')
                                                @slot('id') 
                                                    {{ $client->id }}
                                                @endslot
                                                @endcomponent

                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>

                
            </div>
        </div>
    </section>
<script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script>
$(function () {
    $('#list_table').DataTable({searching: false, "pageLength": 20, "lengthMenu": [ 10, 20, 50 ], "order": [1, 'asc']});
    $(".message-box").fadeTo(6000, 500).slideUp(500, function(){
        $(".message-box").slideUp(500).remove();
    });
});
$('.btn-advanced-search').click(function(){
    for (i=1;i<6;i++){
        if ($('.check_advanced_search'+i).is(':checked')){
            $('.advanced_field'+i).css('display','block');
            $('.advanced_field'+i).attr('disabled',false);
        }else{
            $('.advanced_field'+i).css('display','none');
            $('.advanced_field'+i).attr('disabled',true);
        }
    }
});

</script>

@endsection
